# Simple base64 encoded 16x16 favicon
import base64

# A simple 16x16 favicon (minimal ICO format)
# This is a blue square with white dots representing a link icon
ico_data = base64.b64decode(
    'AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    '82f/wPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wAAAAAAAAAAAAAAAAAAA'
    'AAAAADzZ//A82f/wPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8DzZ//AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ///////////////////////////////82f/wPNn/8AAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A//////////////////////zZ//A82f/wPNn/8AAAAAAAAAAAAAA'
    'AAAAAAAAAPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8AAAAAAAAAA'
    'AAAAAAAAAAAAAPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8DzZ//A82f/wPNn/8AAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wA'
    'A//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP'
    '//AAD//wAA'
)

with open('favicon.ico', 'wb') as f:
    f.write(ico_data)

print("Created favicon.ico")
